/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BooleanDisplay: typeof import('./theme/components/BooleanDisplay.vue')['default']
    MdiArrowRight: typeof import('~icons/mdi/arrow-right')['default']
    RequiresProxy: typeof import('./theme/components/RequiresProxy.vue')['default']
    'Twemoji:faceWithMonocle': typeof import('~icons/twemoji/face-with-monocle')['default']
    'Twemoji:sleepingFace': typeof import('~icons/twemoji/sleeping-face')['default']
  }
}
