name: CI
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.x
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/
          cache: pnpm
      - name: Install and Build
        run: |
          pnpm install
          pnpm docs:build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: ./docs/.vitepress/dist
  sync:
    needs: sync-reload
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:Alfred-Skyblue/vueuse-docs-cn.git"
          destination-repo: "git@gitee.com:alfred-skyblue/vueuse-docs-cn.git"
      - name: reload
        uses: mizuka-wu/gitee-pages-action@v1.0.0
        with:
          repository: alfred-skyblue/vueuse-docs-cn
          cookie: ${{ secrets.GITEE_COOKIE }}
          branch: gh_pages
